# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\administrator.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(469,222)
        Dialog.setStyleSheet("background-color:rgb(54,54,54);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(60, 0, 348, 65))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setMouseTracking(False)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("\n"
"color:rgb(231, 251, 255)")
        self.label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.routine = QtWidgets.QPushButton(Dialog)
        self.routine.setGeometry(QtCore.QRect(20, 90, 131, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.routine.setFont(font)
        self.routine.setStyleSheet("background-color:rgb(85, 255, 255);\n"
"\n"
"")
        self.routine.setObjectName("routine")
        self.teachers = QtWidgets.QPushButton(Dialog)
        self.teachers.setGeometry(QtCore.QRect(170, 90, 131, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.teachers.setFont(font)
        self.teachers.setStyleSheet("background-color:rgb(85, 255, 255);\n"
"\n"
"")
        self.teachers.setObjectName("teachers")
        self.classdetails = QtWidgets.QPushButton(Dialog)
        self.classdetails.setGeometry(QtCore.QRect(320, 90, 131, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.classdetails.setFont(font)
        self.classdetails.setStyleSheet("background-color:rgb(85, 255, 255);\n"
"\n"
"")
        self.classdetails.setObjectName("classdetails")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "ADMINISTRATIVE END"))
        self.routine.setText(_translate("Dialog", "Class Routine"))
        self.teachers.setText(_translate("Dialog", "Teacher Details"))
        self.classdetails.setText(_translate("Dialog", "Class Details"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
