# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys




class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(419, 209)
        Dialog.setStyleSheet("background-color:rgb(54,54,54);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 10, 348, 65))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setMouseTracking(False)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("\n"
"color:rgb(231, 251, 255)")
        self.label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.adminlogin = QtWidgets.QPushButton(Dialog)
        self.adminlogin.setGeometry(QtCore.QRect(30, 90, 161, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.adminlogin.setFont(font)
        self.adminlogin.setStyleSheet("background-color:rgb(85, 255, 255);\n"
"\n"
"")
        self.adminlogin.setObjectName("adminlogin")
        # print(self.adminlogin)
        self.facultylogin = QtWidgets.QPushButton(Dialog)
        self.facultylogin.setGeometry(QtCore.QRect(230, 90, 161, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.facultylogin.setFont(font)
        self.facultylogin.setStyleSheet("background-color:rgb(85, 255, 255);\n"
"\n"
"")
        self.facultylogin.setObjectName("facultylogin")


        self.adminlogin.clicked.connect(self.loginadmin)
        self.facultylogin.clicked.connect(self.loginteacher)
        
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "SCHOOL ANALYTICS DASHBOARD"))
        self.adminlogin.setText(_translate("Dialog", "Administrator"))
        self.facultylogin.setText(_translate("Dialog", "Faculty"))

    def loginadmin(self):
        
        from loginadmin import Ui_Dialog
        
        
        Dialog = QtWidgets.QDialog()
        ui = Ui_Dialog()
        ui.setupUi(Dialog)
        X=Dialog.exec()
        # sys.exit() 
        #    
    def loginteacher(self):
        from loginteacher import Ui_Dialog
        
        
        Dialog = QtWidgets.QDialog()
        ui = Ui_Dialog()
        ui.setupUi(Dialog)
        X=Dialog.exec()
        # sys.exit() 

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
