# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\teacherregistration.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from http.client import OK
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
import mysql.connector


mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  password="",
  database="attendance",
  port=3307
)



class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(393, 508)
        Dialog.setStyleSheet("background-color:rgb(54,54,54);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 10, 348, 65))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setMouseTracking(False)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("\n"
"color:rgb(231, 251, 255)")
        self.label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.registered = QtWidgets.QPushButton(Dialog)
        self.registered.setGeometry(QtCore.QRect(90, 430, 211, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.registered.setFont(font)
        self.registered.setStyleSheet("background-color:rgb(31, 54, 24);\n"
"color:rgb(165, 251, 255)\n"
"\n"
"")
        self.registered.setObjectName("registered")
        self.confirmpassword = QtWidgets.QLineEdit(Dialog)
        self.confirmpassword.setGeometry(QtCore.QRect(180, 390, 133, 20))
        self.confirmpassword.setStyleSheet("background-color:rgb(221, 255, 254)")
        self.confirmpassword.setText("")
        self.confirmpassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirmpassword.setObjectName("confirmpassword")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(30, 370, 152, 59))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:rgb(165, 251, 255)")
        self.label_6.setObjectName("label_6")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 300, 401, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:rgb(165, 251, 255)")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.password = QtWidgets.QLineEdit(self.layoutWidget)
        self.password.setStyleSheet("background-color:rgb(221, 255, 254)")
        self.password.setText("")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.horizontalLayout.addWidget(self.password)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 230, 391, 61))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgb(165, 251, 255)")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.username = QtWidgets.QLineEdit(self.layoutWidget1)
        self.username.setStyleSheet("background-color:rgb(221, 255, 254)")
        self.username.setText("")
        self.username.setObjectName("username")
        self.horizontalLayout_2.addWidget(self.username)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.layoutWidget2 = QtWidgets.QWidget(Dialog)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 150, 391, 61))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(165, 251, 255)")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lastname = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lastname.setStyleSheet("background-color:rgb(221, 255, 254)")
        self.lastname.setText("")
        self.lastname.setObjectName("lastname")
        self.horizontalLayout_3.addWidget(self.lastname)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.layoutWidget3 = QtWidgets.QWidget(Dialog)
        self.layoutWidget3.setGeometry(QtCore.QRect(0, 70, 391, 61))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(165, 251, 255)")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.firstname = QtWidgets.QLineEdit(self.layoutWidget3)
        self.firstname.setStyleSheet("background-color:rgb(221, 255, 254)")
        self.firstname.setText("")
        self.firstname.setObjectName("firstname")
        self.horizontalLayout_4.addWidget(self.firstname)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)

        

        self.registered.clicked.connect(self.regist)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Registration Form"))
        self.registered.setText(_translate("Dialog", "Click here to Register"))
        self.label_6.setText(_translate("Dialog", "Confirm password:"))
        self.label_5.setText(_translate("Dialog", "Password:"))
        self.label_4.setText(_translate("Dialog", "Username:"))
        self.label_3.setText(_translate("Dialog", "Last name:"))
        self.label_2.setText(_translate("Dialog", "First name:"))

    def regist(self):
        firstname = self.firstname.text()
        lastname=self.lastname.text()
        username = self.username.text()
        print(username)
        password = self.password.text()
        confirmpassword = self.confirmpassword.text()
        mycursor = mydb.cursor()
        checkUserNamesql = f'SELECT * FROM faculty WHERE username ="{username}"'
        mycursor.execute(checkUserNamesql)
        myresult = mycursor.fetchall()
        print(myresult)
        
        
        
        if (len(myresult) == 0):
            if (password == confirmpassword):
                sql = "INSERT INTO faculty (first_name, last_name, username, password) VALUES ('"+firstname+"', '"+lastname+"', '"+username+"', '"+password+"')"
                mycursor.execute(sql)
                mydb.commit()
                msg=QMessageBox()
                msg.setText("Registration successful")
                msg.setWindowTitle("show info")
                msg.setStandardButtons(QMessageBox.Ok)
                retval=msg.exec_()
                if OK:
                    from teacherend import Ui_Dialog
                    Dialog = QtWidgets.QDialog()
                    ui = Ui_Dialog()
                    ui.setupUi(Dialog)
                    X=Dialog.exec()  
                
            else: 
                msg=QMessageBox()
                msg.setText("Password and confirm password need to be same.")
                msg.setWindowTitle("error")
                msg.setStandardButtons(QMessageBox.Ok)
                retval=msg.exec_()
        else: 
            # self.popup( "Username already registered.")
            msg=QMessageBox()
            msg.setText("Username already registered.")
            msg.setWindowTitle("error")
            msg.setStandardButtons(QMessageBox.Ok)
            retval=msg.exec_()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
